### ISSUE TITLE
Error when running video_to_image.py

### ISSUE THREAD

**Issue by ZhangRenkai** [CHUNYUWANG/H36M-Toolbox#3]
when running this code, there exists error FileNotFoundError: [WinError 2], and I don't know how to tackle it.
The detail message are as follows.
``
Traceback (most recent call last):
  File "video_to_images.py", line 40, in <module>
    call([
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
``
Thank you very much!

**Comment by liuhaoyuyh** [comment]
I have encountered the same problem. How did you solve it
